"""align existing schema constraints

Revision ID: d7bcf50b8e4d
Revises: 
Create Date: 2026-09-18 10:27:58.385002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7bcf50b8e4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_budgets_id'),
            ['id'],
            unique=False
        )
        batch_op.create_foreign_key(
            'fk_budgets_user_id_users',
            'users',
            ['user_id'],
            ['id']
        )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(
            'fk_expenses_user_id_users',
            'users',
            ['user_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_expenses_user_id_users',
            type_='foreignkey'
        )
        batch_op.alter_column(
            'user_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_budgets_user_id_users',
            type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_budgets_id'))
    # ### end Alembic commands ###
